parameters:
#    reto_aprender.example.class: Tecnotek\RetoAprenderBundle\Example

services:
#    reto_aprender.example:
#        class: %reto_aprender.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    tecnotek.reto_aprender.twig.resources_menu_extension:
            class: Tecnotek\RetoAprenderBundle\Twig\Extensions\ResourcesMenuExtension
            tags:
                - { name: twig.extension }
            arguments:
                em: "@doctrine.orm.entity_manager"
    tecnotek.reto_aprender.login.listener:
                class: Tecnotek\RetoAprenderBundle\Event\LoginEventListener
                tags:
                    - { name: kernel.event_listener,  event: security.interactive_login }
                arguments:
                    em: "@doctrine.orm.entity_manager"